GitHub Actionsで更新
kota-yata/Syllabus-proto pull request #3
Opened 2024-03-13 12:56 UTC by kota113

2024-03-13 13:23 UTC, kota-yata requested changes
[kota113:masterのActions](https://github.com/kota113/Syllabus-proto/actions/runs/8262297124)見たかぎり動いてそうなのでマージしたいのですが、その前に前のコントリビューターが残した不必要なコメントを消していただけると大変助かります🙏

2024-03-13 13:23 UTC, kota-yata commented on scripts/syllabusScraping.py
> +        # 情報を抽出。このエラーハンドリングもっとうまく誰か書けよクソが
こことか

2024-03-13 13:23 UTC, kota-yata commented on scripts/syllabusScraping.py
> -        #ここら辺手抜きすぎるから、また直そうね
こことか

2024-03-14 03:47 UTC, kota113 commented on scripts/syllabusScraping.py
> -        #ここら辺手抜きすぎるから、また直そうね
そこ既に削ってます！

2024-03-14 03:47 UTC, kota113 commented on scripts/syllabusScraping.py
> +        # 情報を抽出。このエラーハンドリングもっとうまく誰か書けよクソが
消しました。Done👍

2024-03-14 04:29 UTC, kota113 commented
コメント削除しました。
念のため[テスト](https://github.com/kota113/Syllabus-proto/commit/5765f94b04b90d7709a11517a03115927d639672)したんですが大丈夫そうです。

2024-03-14 04:56 UTC, kota-yata approved these changes
LGTM!

2024-03-14 04:56 UTC, merged